new datasets for emissions profile
2DegreesInvesting/tiltToyData pull request #19
Opened 2023-12-23 16:19 UTC by maurolepore

- New emissions*products_ecoinvent
- New helpers
- Test
- Render README

----

TODO

- [ ] [Link related issue/PR]([url](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). 
- [ ] Describe the goal of the PR. Avoid details that are clear in the diff.
- [ ] Mark the PR as draft.
- [ ] [Include a unit test](https://code-review.tidyverse.org/reviewer/aspects.html#sec-tests).
- [ ] Review your own PR in "Files changed".
- [ ] Ensure the PR branch is updated.
- [ ] Ensure the checks pass.
- [ ] Change the status from draft to ready.
- [ ] Polish the PR title and description.
- [ ] Assign a reviewer.

EXCEPTIONS

- [ ] Slide here any item that you intentionally choose to not do.

2024-01-05 15:05 UTC, maurolepore commented on NAMESPACE
> +export(toy_emissions_profile_upstream_products_ecoinvent)
TODO: Report in NEWS.

2024-01-05 15:05 UTC, maurolepore commented on inst/extdata/deprecated/emissions_profile_any_companies.csv.gz
TODO: Report in NEWS the new version of this dataset.

2024-01-05 17:34 UTC, maurolepore commented
@kalashsinghal when you review this PR note the new datasets have columns that the old datasets don't have. Are they all necessary?

``` r
devtools::load_all()
#> ℹ Loading tiltToyData
library(readr, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)

# companies
new <- read_csv(toy_emissions_profile_any_companies())
old <- read_csv(deprecated_path("emissions_profile_any_companies.csv.gz"))
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "country"          "ei_activity_name" "main_activity"

# products
old <- read_csv(toy_emissions_profile_products())
new <- read_csv(toy_emissions_profile_products_ecoinvent())
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "ei_geography"

# upstrem_products
old <- read_csv(toy_emissions_profile_upstream_products())
new <- read_csv(toy_emissions_profile_upstream_products_ecoinvent())
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "ei_geography"                 "input_reference_product_name"
```

<sup>Created on 2024-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2024-01-07 12:40 UTC, kalashsinghal requested changes
LGTM

> when you review this PR note the new datasets have columns that the old datasets don't have. Are they all necessary?

@maurolepore Yes they all are necessary for for an analyst to analyse the data quality from tiltIndicatorBefore. Hence, these columns should remain in the outputs from tiltIndicatorBefore. 

Moreover, `toy_emissions_profile_upstream_products_ecoinvent` should have these two more columns in the toy datasets: `ei_activity_name` and `input_ei_activity_name` which you haven't included. Please add these two columns as well with any random values because they will not be used in tiltIndicator. Thanks!

2024-01-08 13:00 UTC, maurolepore commented
Thanks @Kalash,

Can you please share a link to the latest datasets?

The raw data I used seems to lack the columns you want. And the original link you shared seems to no longer be valid: See lines 31, 47, and 51 of this file:
https://github.com/2DegreesInvesting/tiltToyDataPrivate/blob/main/data-raw/emissions_profile-copy_relevant_rows.R

They all say "Sorry, the file you have requested does not exist."

2024-01-08 14:30 UTC, maurolepore commented
I updated the datasets with those from https://drive.google.com/drive/folders/1AbSGCGFVcRM3zLfPg5FdwScTRRaCbIws. Now `emissions_profile_upstream_products_ecoinvent.csv` has the `*activity_name` columns.


``` r
devtools::load_all()
#> ℹ Loading tiltToyData
library(readr, warn.conflicts = FALSE)
options(readr.show_col_types = FALSE)

# companies
new <- read_csv(toy_emissions_profile_any_companies())
old <- read_csv(deprecated_path("emissions_profile_any_companies.csv.gz"))
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "country"          "ei_activity_name" "main_activity"

# products
old <- read_csv(toy_emissions_profile_products())
new <- read_csv(toy_emissions_profile_products_ecoinvent())
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "ei_geography"

# upstrem_products
old <- read_csv(toy_emissions_profile_upstream_products())
new <- read_csv(toy_emissions_profile_upstream_products_ecoinvent())
setdiff(names(old), names(new))
#> character(0)
setdiff(names(new), names(old))
#> [1] "ei_activity_name"             "ei_geography"                
#> [3] "input_ei_activity_name"       "input_reference_product_name"
```

<sup>Created on 2024-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2024-01-08 14:52 UTC, kalashsinghal approved these changes
LGTM

2024-01-08 14:58 UTC, maurolepore commented
@kalashsinghal 

Thanks!

 RE: 

> Please add these two columns as well with any random values because they will not be used in tiltIndicator. 

I didn't randomize the values as I believe those columns they are not private data in themselves. Please let me know if you think they should indeed be random, or if we need to ask Anne.

What IS random and fake in these datasets is this:

* Fake `companies_id`.
* Fake `activity_uuid_product_uuid`.
* Random mapping between fake `activity_uuid_product_uuid` and other columns.
* Noisy `*co2_footprint`, jittered to the right by 50%-100% on average.

2024-01-09 19:12 UTC, maurolepore commented
FIXME

The `*isic*` column has the wrong quoting.

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
devtools::load_all()
#> ℹ Loading tiltToyData

options(readr.show_col_types = FALSE, width = 500)

products <- read_csv(toy_emissions_profile_products_ecoinvent())
products |> 
  relocate(matches("isic"))
#> # A tibble: 18 × 8
#>    isic_4digit activity_uuid_product_uuid           co2_footprint ei_activity_name                                              ei_geography tilt_sector  tilt_subsector           unit 
#>    <chr>       <chr>                                        <dbl> <chr>                                                         <chr>        <chr>        <chr>                    <chr>
#>  1 ''2410''    833caa78-30df-4374-900f-7f88ab44075b        14.1   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  2 ''2591''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb         0.419 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  3 ''4100''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       481.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#>  4 ''2410''    833caa78-30df-4374-900f-7f88ab44075b         9.47  iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  5 ''2591''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb         0.648 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  6 ''4100''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       276.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#>  7 ''2410''    833caa78-30df-4374-900f-7f88ab44075b        13.6   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  8 ''2591''    76269c17-78d6-420b-991a-aa38c51b45b7         0.405 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  9 ''4100''    76269c17-78d6-420b-991a-aa38c51b45b7       447.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 10 ''2410''    833caa78-30df-4374-900f-7f88ab44075b        14.7   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 11 ''2591''    833caa78-30df-4374-900f-7f88ab44075b         0.390 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 12 ''4100''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       442.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 13 ''2410''    76269c17-78d6-420b-991a-aa38c51b45b7        14.1   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 14 ''2591''    76269c17-78d6-420b-991a-aa38c51b45b7         0.884 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 15 ''4100''    76269c17-78d6-420b-991a-aa38c51b45b7       321.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 16 ''2410''    833caa78-30df-4374-900f-7f88ab44075b        12.7   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 17 ''2591''    76269c17-78d6-420b-991a-aa38c51b45b7         0.675 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 18 ''4100''    bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       435.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2


upstream_products <- read_csv(toy_emissions_profile_upstream_products_ecoinvent())
upstream_products |> 
  relocate(matches("isic"))
#> # A tibble: 96 × 11
#>    input_isic_4digit activity_uuid_product_uuid           ei_activity_name                                              ei_geography                      input_activity_uuid_product_uuid                                          input_co2_footprint input_ei_activity_name                                          input_reference_product_name                       input_tilt_sector input_tilt_subsector     input_unit
#>    <chr>             <chr>                                <chr>                                                         <chr>                             <chr>                                                                                   <dbl> <chr>                                                           <chr>                                              <chr>             <chr>                    <chr>     
#>  1 ''2591''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb market for deep drawing, steel, 10000 kN press, automode      RoW                               55a5ac05-ab15-5a27-9d0e-6ecf840039f1_f10b8722-4be1-43d5-b17d-c51ad0e29d29             4.56e-1 deep drawing, steel, 10000 kN press, automode                   deep drawing, steel, 10000 kN press, automode      metals            other metals             kg        
#>  2 ''4100''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb market for shed, large, wood, non-insulated, fire-unprotected RoW                               bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df             4.63e+2 shed construction, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected construction      construction residential m2        
#>  3 ''2790''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         GLO                               bdc93cd8-00b4-5b3e-993e-b7fef7059e52_4e584f6f-2e71-4796-931e-bb9a273c161c             1.67e+0 market for anode, for metal electrolysis                        anode, for metal electrolysis                      industry          machinery & equipment    kg        
#>  4 ''2815''          76269c17-78d6-420b-991a-aa38c51b45b7 iron-nickel-chromium alloy production                         RER                               fdb1f848-173f-5fe1-96a2-588171e87e30_c2c93af2-47cb-4ec7-a1bd-d3d572bca039             1.45e+8 electric arc furnace converter construction                     electric arc furnace converter                     industry          other industry           unit      
#>  5 ''3821''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               95fcd1bb-4dc6-516a-a3b2-30a4f0530639_3b1d249a-c924-4d6c-8e1f-647f562daa54             5.30e-1 market for electric arc furnace dust                            electric arc furnace dust                          industry          other industry           kg        
#>  6 ''3821''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               daef2f9a-4108-52ae-90a7-fe64abad51bc_6e74937e-b691-4c49-9b8f-5ba44d7c081d             5.89e-1 market for electric arc furnace slag                            electric arc furnace slag                          industry          other industry           kg        
#>  7 ''3510''          bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               3b190359-a32e-5294-af63-983f38ce6525_759b89bd-3aa6-42ad-b767-5bb9ef5d331d             6.02e-1 market group for electricity, medium voltage                    electricity, medium voltage                      [...]

2024-01-09 20:12 UTC, maurolepore commented
FIXED

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
devtools::load_all()
#> ℹ Loading tiltToyData

options(readr.show_col_types = FALSE, width = 1000)

products <- read_csv(toy_emissions_profile_products_ecoinvent())
products |> relocate(matches("isic"))
#> # A tibble: 18 × 8
#>    isic_4digit activity_uuid_product_uuid           co2_footprint ei_activity_name                                              ei_geography tilt_sector  tilt_subsector           unit 
#>    <chr>       <chr>                                        <dbl> <chr>                                                         <chr>        <chr>        <chr>                    <chr>
#>  1 '2410'      833caa78-30df-4374-900f-7f88ab44075b        14.1   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  2 '2591'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb         0.419 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  3 '4100'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       481.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#>  4 '2410'      833caa78-30df-4374-900f-7f88ab44075b         9.47  iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  5 '2591'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb         0.648 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  6 '4100'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       276.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#>  7 '2410'      833caa78-30df-4374-900f-7f88ab44075b        13.6   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#>  8 '2591'      76269c17-78d6-420b-991a-aa38c51b45b7         0.405 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#>  9 '4100'      76269c17-78d6-420b-991a-aa38c51b45b7       447.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 10 '2410'      833caa78-30df-4374-900f-7f88ab44075b        14.7   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 11 '2591'      833caa78-30df-4374-900f-7f88ab44075b         0.390 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 12 '4100'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       442.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 13 '2410'      76269c17-78d6-420b-991a-aa38c51b45b7        14.1   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 14 '2591'      76269c17-78d6-420b-991a-aa38c51b45b7         0.884 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 15 '4100'      76269c17-78d6-420b-991a-aa38c51b45b7       321.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2   
#> 16 '2410'      833caa78-30df-4374-900f-7f88ab44075b        12.7   iron-nickel-chromium alloy production                         RER          metals       iron & steel             kg   
#> 17 '2591'      76269c17-78d6-420b-991a-aa38c51b45b7         0.675 market for deep drawing, steel, 10000 kN press, automode      GLO          metals       other metals             kg   
#> 18 '4100'      bf94b5a7-b7a2-46d1-bb95-84bc560b12fb       435.    market for shed, large, wood, non-insulated, fire-unprotected GLO          construction construction residential m2

inputs <- read_csv(toy_emissions_profile_upstream_products_ecoinvent())
inputs |> relocate(matches("isic"))
#> # A tibble: 96 × 11
#>    input_isic_4digit activity_uuid_product_uuid           ei_activity_name                                              ei_geography                      input_activity_uuid_product_uuid                                          input_co2_footprint input_ei_activity_name                                          input_reference_product_name                       input_tilt_sector input_tilt_subsector     input_unit
#>    <chr>             <chr>                                <chr>                                                         <chr>                             <chr>                                                                                   <dbl> <chr>                                                           <chr>                                              <chr>             <chr>                    <chr>     
#>  1 '2591'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb market for deep drawing, steel, 10000 kN press, automode      RoW                               55a5ac05-ab15-5a27-9d0e-6ecf840039f1_f10b8722-4be1-43d5-b17d-c51ad0e29d29             4.56e-1 deep drawing, steel, 10000 kN press, automode                   deep drawing, steel, 10000 kN press, automode      metals            other metals             kg        
#>  2 '4100'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb market for shed, large, wood, non-insulated, fire-unprotected RoW                               bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df             4.63e+2 shed construction, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fire-unprotected construction      construction residential m2        
#>  3 '2790'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         GLO                               bdc93cd8-00b4-5b3e-993e-b7fef7059e52_4e584f6f-2e71-4796-931e-bb9a273c161c             1.67e+0 market for anode, for metal electrolysis                        anode, for metal electrolysis                      industry          machinery & equipment    kg        
#>  4 '2815'            76269c17-78d6-420b-991a-aa38c51b45b7 iron-nickel-chromium alloy production                         RER                               fdb1f848-173f-5fe1-96a2-588171e87e30_c2c93af2-47cb-4ec7-a1bd-d3d572bca039             1.45e+8 electric arc furnace converter construction                     electric arc furnace converter                     industry          other industry           unit      
#>  5 '3821'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               95fcd1bb-4dc6-516a-a3b2-30a4f0530639_3b1d249a-c924-4d6c-8e1f-647f562daa54             5.30e-1 market for electric arc furnace dust                            electric arc furnace dust                          industry          other industry           kg        
#>  6 '3821'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               daef2f9a-4108-52ae-90a7-fe64abad51bc_6e74937e-b691-4c49-9b8f-5ba44d7c081d             5.89e-1 market for electric arc furnace slag                            electric arc furnace slag                          industry          other industry           kg        
#>  7 '3510'            bf94b5a7-b7a2-46d1-bb95-84bc560b12fb iron-nickel-chromium alloy production                         RER                               3b190359-a32e-5294-af63-983f38ce6525_759b89bd-3aa6-42ad-b767-5bb9ef5d331d             6.02e-1 market group for electricity, medium voltage                    electricity, medium voltage                        power             total power              kWh       
#>  8 '2410'    [...]

2024-01-09 21:03 UTC, maurolepore commented
@Tilmon,

Resuming today's conversation about making sure that the toy data is public. 

@kalashsinghal added a few columns that didn't exist in the old datasets ([comparison between the columns in old versus new datasets](https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1881121703)). This means we'll publish some columns which privacy we didn't discuss  before. In particular Kalash was worried about the `*activity_name` columns. 

I look forward to documenting the details of licensed columns. But from what you said today I believe the toy datasets in this PR are OK because among other features (see them all in the top comment) these datasets have:

* Fake `activity_uuid_product_uuid`.
* Random mapping between fake `activity_uuid_product_uuid` and other columns.

The implementation of these features happen in the tiltToyPrivate data package via the `randimize_uuid()` function ([source](https://github.com/2DegreesInvesting/tiltToyDataPrivate/blob/2781b0f1814e8f3ea8f2364d55fa1170788a9507/data-raw/emissions_profile-toy.R#L20), [application](https://github.com/2DegreesInvesting/tiltToyDataPrivate/blob/2781b0f1814e8f3ea8f2364d55fa1170788a9507/data-raw/emissions_profile-toy.R#L42)). If you explore its source code you'll see that it first replaces `*uuid` with fake values and then shuffles them (via `sample()`) to break the link between `activity_uuid_product_uuid` and other columns. 

The following reprex shows the result. Focus on the relationship between the colum `clustered` and `ei_activity_name`. That relationship doesn't always make sense, giving evidence that the link is broken. A caveat is that the toy data is very small so the pool of `*uuid` that we shuffled is small too, meaning that it's not hard to re-arrange the broken link using just common sense. 

If this worries you we can discuss how to continue before we merge this PR. A quick alternative for now might be able to remove the additional columns if @kalashsinghal things we can live without them for now (I don't know how exactly they will be used).

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
devtools::load_all()
#> ℹ Loading tiltToyData

options(readr.show_col_types = FALSE, width = 1000)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products_ecoinvent())

left_join(companies, products, relationship = "many-to-many") |> 
  select(matches(c("uuid", "activity_name")), clustered)
#> Joining with `by = join_by(activity_uuid_product_uuid, ei_activity_name, unit)`
#> # A tibble: 155 × 3
#>    activity_uuid_product_uuid           ei_activity_name                                              clustered                  
#>    <chr>                                <chr>                                                         <chr>                      
#>  1 76269c17-78d6-420b-991a-aa38c51b45b7 market for shed, large, wood, non-insulated, fire-unprotected tent                       
#>  2 76269c17-78d6-420b-991a-aa38c51b45b7 market for shed, large, wood, non-insulated, fire-unprotected tent                       
#>  3 76269c17-78d6-420b-991a-aa38c51b45b7 market for shed, large, wood, non-insulated, fire-unprotected table hire for parties     
#>  4 76269c17-78d6-420b-991a-aa38c51b45b7 market for shed, large, wood, non-insulated, fire-unprotected table hire for parties     
#>  5 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface finishing, galvanic
#>  6 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface finishing, galvanic
#>  7 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface finishing, galvanic
#>  8 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface engineering        
#>  9 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface engineering        
#> 10 76269c17-78d6-420b-991a-aa38c51b45b7 market for deep drawing, steel, 10000 kN press, automode      surface engineering        
#> # ℹ 145 more rows

inputs <- read_csv(toy_emissions_profile_upstream_products_ecoinvent())

left_join(companies, inputs, relationship = "many-to-many") |> 
  select(matches(c("uuid", "activity_name")), clustered)
#> Joining with `by = join_by(activity_uuid_product_uuid, ei_activity_name)`
#> # A tibble: 97 × 5
#>    activity_uuid_product_uuid           input_activity_uuid_product_uuid                                          ei_activity_name                                              input_ei_activity_name                                          clustered                  
#>    <chr>                                <chr>                                                                     <chr>                                                         <chr>                                                           <chr>                      
#>  1 76269c17-78d6-420b-991a-aa38c51b45b7 bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#>  2 76269c17-78d6-420b-991a-aa38c51b45b7 bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected table hire for parties     
#>  3 76269c17-78d6-420b-991a-aa38c51b45b7 <NA>                                                                      market for deep drawing, steel, 10000 kN press, automode      <NA>                                                            surface finishing, galvanic
#>  4 76269c17-78d6-420b-991a-aa38c51b45b7 <NA>                                                                      market for deep drawing, steel, 10000 kN press, automode      <NA>                                                            surface engineering        
#>  5 76269c17-78d6-420b-991a-aa38c51b45b7 bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#>  6 76269c17-78d6-420b-991a-aa38c51b45b7 bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#>  7 76269c17-78d6-420b-991a-aa38c51b45b7 bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected open space amenities       
#>  8 bf94b5a7-b7a2-46d1-bb95-84bc560b12fb bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#>  9 bf94b5a7-b7a2-46d1-bb95-84bc560b12fb bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#> 10 bf94b5a7-b7a2-46d1-bb95-84bc560b12fb bc548877-9cc6-590d-ba72-1d1d2daeb5b9_e2ccc500-255f-448c-8c88-ed25177993df market for shed, large, wood, non-insulated, fire-unprotected shed construction, large, wood, non-insulated, fire-unprotected tent                       
#> # ℹ 87 more rows
```

<sup>Created on 2024-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

2024-01-10 10:59 UTC, kalashsinghal commented
> If this worries you, we can discuss how to continue before we merge this PR. A quick alternative for now might be able to remove the additional columns if @kalashsinghal thinks we can live without them for now (I don't know how exactly they will be used).

@maurolepore Anne needed these additional columns in the past for her own analysis on the tiltIndicatorBefore outputs. Its not feasible to use any untraceable code to add these columns and then provide the output to Anne's analysis in the future. Hence, I highly recommend to have these columns in the final output of tiltIndicatorBefore. 

Also, @maurolepore You can use any fake data to add these columns in the toy data irrespective of how these additional columns are linked to the licensed data. I am asking to do so because these additional columns are not used in tiltIndicator and tiltIndicatorAfter in any way, and also an external user don't need to see the real values of such columns. right @Tilmon? Please confirm this! Thanks! :)

2024-01-10 11:46 UTC, AnneSchoenauer commented
@maurolepore - thanks a lot for taking already the initiatve with seeing if there are some uuids not in one dataset but in the ohter. I created before I saw [your comment](https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1883724594) here this [ticket ](https://github.com/2DegreesInvesting/tiltToyData/issues/22)with a reprex to show you why this requirement is so important. Maybe it also helps you. You can close it if it is all clear. 

For your questions to @Tilmon - wasn't this the reason why we now have the jitter function as well for the co2 data? However, yes most likely not covering all licensed data. Good to make here a proper check before publishing .

2024-01-10 18:31 UTC, maurolepore commented
> @maurolepore Anne needed these additional columns in the past for her own analysis on the tiltIndicatorBefore outputs.
> ... these additional columns are not used in tiltIndicator and tiltIndicatorAfter in any way

Thanks @kalashsinghal. This seems usage of those columns seems very internal -- equivalent to a developer-oriented internal function that users don't need to know about.

@AnneSchoenauer to refresh your memory, this PR would  introduce the following new columns in public toy datasets (for details see also [Comparing columns between old and new datasets](https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1881121703) above):

```r
# emissions_profile_any_companies
#> [1] "country"          "ei_activity_name" "main_activity"

# emissions_profile_products_ecoinvent
#> [1] "ei_geography"

# emissions_profile_upstream_products_ecoinvent
#> [1] "ei_activity_name"             "ei_geography"                
#> [3] "input_ei_activity_name"       "input_reference_product_name"
```

Do you need these columns to appear in the public toy datasets that we use in all our websites to shows examples to our users?

From what Kalash says they are not useful for most users of our packages. We can keep them and ensure they don't expose private data, but it's best to make public as little as possible. It's always best to release as little stuff as possible. Adding things later is easy. Removing them later is hard -- we need to go through an expensive deprecation process to ensure backward compatibility.

2024-01-10 21:52 UTC, AnneSchoenauer commented
@Tilmon what do you think? These data points are not needed for the tiltIndicator but are needed for the output files. So they are needed to produce the outputs from tiltIndicatorAfter. I hear @maurolepore though that it is expensive to have them in in the toydataset. @Tilmon  what do you think is better from a transparency and usability perspective?

2024-01-11 14:19 UTC, maurolepore commented
@AnneSchoenauer 

> These data points ... are needed for the output files

Okay, then this suggests a more public usage than what I understand from Kalash's comments. If users expect those columns in the output then they seem to deserve a place in the toy datasets. And tiltIndicatorAfter should have a test to ensure these columns exist in the output (cc' @kalashsinghal).

Assuming the columns stay, then the last question we need to resolve is [this](url):

* Are you okay with the columns "as is" or do we need to solve any privacy issue?

See https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1883788387 

I look forward to your answers so we can merge this PR ASAP and and close the many related issues.

2024-01-11 14:58 UTC, AnneSchoenauer commented
Great!

@Tilmon could you please answer this [here](https://github.com/2DegreesInvesting/tiltToyData/pull/19#issuecomment-1883788387). I think you are best invovled with the licenses issues in ecoinvent. 

Thanks!!

2024-01-11 15:35 UTC, kalashsinghal commented
> These data points are not needed for the tiltIndicator but are needed for the output files. So they are needed to produce the outputs from tiltIndicatorAfter.

@AnneSchoenauer Based on your comment here, Should I ensure that all these extra columns from tiltIndicatorBefore also be present in the final output from tiltIndicatorAfter? If yes, then I will create a separate ticket for it in tiltIndicatorAfter package. FYI: At the moment not all of those extra columns are present in the final output.

2024-01-11 15:41 UTC, AnneSchoenauer commented
@kalashsinghal yes sounds good!

2024-01-11 17:32 UTC, Tilmon commented
Hi @AnneSchoenauer @kalashsinghal @maurolepore sorry for the late response and thanks for already clarifying almost everything. 

Re

> I look forward to documenting the details of licensed columns. But from what you said today I believe the toy datasets in this PR are OK (but see CAVEAT below) because among other features (see them all in the top comment) these datasets have:
> - Fake activity_uuid_product_uuid.
> - Random mapping between fake activity_uuid_product_uuid and other columns.

That's fine! It's important that we don't share the real co2 data, which we don't, because it's jittered. Also it's important to not share which `input_activity_uuid_product_uuid `belong to which `activity_uuid_product_uuid`, which is not the case because: 

- activity_uuid_product_uuid  is fake
- activity_uuid_product_uuid is shuffled around so that link to other variables are broken. 

Note for future reference (will also send this in an email as discussed to the whole team): the `activity_uuid_product_uuid `is defined by the combination activity_name x `reference_product `x `geography `x `main_activity`. Meaning that if you fake the `activity_uuid_product_uuid ` but show all other four columns users can create the `activity_uuid_product_uuid `by themselves. 
In the toy data that you referenced, not all 4 columns aside from the `activity_uuid_product_uuid ` are shown, so all is fine. 

@maurolepore you pointed out that the toy data is small and one could try to re-shuffle it to get licensed information but they won't be able to define the exact `activity_uuid_product_uuid` as too many of the other 4 variables are missing. 

Thanks for your efforts to create the toydata in a compliant way with our license agreement @maurolepore and @kalashsinghal !

2024-01-11 21:01 UTC, merged

2024-01-12 08:44 UTC, maurolepore commented
@AnneSchoenauer, I think the best person to answer is @Tilmon. But if the final output will have all the columns and the shuffling doesn't break licensed links, then it seems like a problem. If so let me know which columns we could replace with fake values.

2024-01-12 10:13 UTC, AnneSchoenauer commented
Yes I agree - @Tilmon we can also discuss later but I think it will be a problem indeed.

2024-01-12 11:17 UTC, Tilmon commented
@AnneSchoenauer good point. I checked the tiltIndicator and tiltIndicatorAfter outputs and what I see is that in

- in **tiltIndicator**, the [emission profile upstream indicator](https://2degreesinvesting.github.io/tiltIndicator/reference/emissions_profile_upstream.html) , the data contain both `activity_uuid_product_uuid `and `input_activity_uuid_product_uuid`. This information should not be available to users without a license. Aside from the `input_activity_uuid_product_uuid`, there is no input-related variable to identify the unique input. How can we solve that not both `activity_uuid_product_uuid `and `input_activity_uuid_product_uuid` are shown here? @maurolepore could we create an internal ID mapping, where we create our own ID for each `input_activity_uuid_product_uuid ` and just show our own ID instead of ecoinvent's `input_activity_uuid_product_uuid `? For users with license, we could share the mapper of our own IDs with `input_activity_uuid_product_uuid `.
- in **tiltIndicatorAfter**, the [emission profile upstream](https://2degreesinvesting.github.io/tiltIndicatorAfter/reference/profile_emissions_upstream.html) does not contain the `input_activity_uuid_product_uuid `, but only the input-related variables `input_name`, `input_unit`, `input_tilt_sector`, `input_tilt_subsector`, `input_isic_4digit`, `input_isic_4digit_name` which is not enough info to define a unique `input_activity_uuid_product_uuid`.

What do you think @AnneSchoenauer @maurolepore? Does it make sense to create fake IDs for the users and keep the real IDs for ourselves?

2024-01-12 11:21 UTC, AnneSchoenauer commented
Yes it does! @maurolepore do you think you could do this? 

We are getting there!!!

2024-01-12 12:39 UTC, kalashsinghal commented
@Tilmon I would also like to add that columns `ei_activity_name` and `ei_input_geography` will also be added to the final output of emission profile upstream indicator at product level. Will they can cause any issue?

2024-01-12 13:57 UTC, maurolepore commented
Dear all,

Although it seems like this conversation still needs to continue to make our toy datasets perfect, I go with the saying "perfect is the enemy of the good". This PR already represents a significant improvement and if anything private is exposed, it is less than before. 

The condition to merge a PR is that (1) it doesn't make things worse and (2) it does make things better. So I went ahead and merged this PR. This allows us to move on with the very many related issues that depend on this one. 

In short, as the top comment says the main features of this PR are these:

* Fake companies_id`.
* Fake `activity_uuid_product_uuid`.
* Random mapping between `fake activity_uuid_product_uuid` and other columns.
* Noisy `*co2_footprint`, jittered to the right by 50%-100% on average.
* New columns.

We can now start from good and more to perfect here: #24